defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: simple_qa_development

test:
  <<: *defaults
  database: simple_qa_test

# set these environment variables on your prod server
production:
  <% if ENV['MONGOHQ_URL'] %>
  uri: <%= ENV['MONGOHQ_URL'] %>
  <% elsif ENV['VCAP_SERVICES'] && 
       credentials = JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-1.8'].first['credentials'] %>
  <<: *defaults
  host: <%= credentials['hostname'] %>
  port: <%= credentials['port'] %>
  database: <%= credentials['db'] %>
  username: <%= credentials['username'] %>
  password: <%= credentials['password'] %>
  <% end %>
